Makefile, orchestration/Dockerfile, orchestration/Makefile, parser/Dockerfile, parser/Makefile, parserlang/golang/Dockerfile, parserlang/golang/Makefile, parserlang/java/Dockerfile, parserlang/java/Makefile, parserlang/nodejs/Dockerfile, parserlang/nodejs/Makefile, parserlang/python/Dockerfile, parserlang/python/Makefile, scripts/build-images.sh, server/Dockerfile, server/Makefile, web/Makefile
Reverts bazooka-ci/bazooka#133
=> Revert "Update build to run on Docker Hub"

scripts/build-devimages.sh, scripts/build-images.sh, scripts/build-runner.sh, scripts/build-scm.sh
These scripts should only be execute with make.
=> Remove use of GOPATH on build-*.sh

cli/bzk/bzk.go, cli/bzk/config.go, cli/bzk/image.go, cli/bzk/input.go, cli/bzk/job.go, cli/bzk/key.go, cli/bzk/login.go, cli/bzk/project.go, cli/bzk/run.go, cli/bzk/user.go, cli/bzk/variant.go
=> Prompt BZK env vars when none found

Makefile, cli/Makefile, orchestration/Makefile, parser/Makefile, server/Makefile
=> Ensure that commons and its subpackages get installed before building the cli, server, orhcestration or parser

commons/mongo/project.go, server/project.go
Multiple projects with the same scmURI can be created!
=> scm_uri is no longer unique

server/job.go
Remove the orchestrator container at the end of a job.
=> Remove the orchestrator container at the end of a job

web/src/utils/utils.js
=> Escape html tags in job and variant logs

cli/bzk/service.go
Take care, running bzk service restart will wipe all your data after this
=> Set mongo container version to a fixed version

client/job.go
=> Add a get job by id function to the bazooka client

cli/bzk/job.go, cli/bzk/variant.go, client/client.go, client/commons_log.go, client/job.go, client/variant.go, commons/mongo/project.go, server/job.go, server/main.go, server/server.go, server/variant.go
The CLI command `job log` and `variant log` also gained a `--follow` flag to use the log streaming feature
=> Handle variant and job log streaming

web/src/project/_project.scss, web/src/project/project.html, web/src/project/projectController.js, web/src/styles.scss, web/src/utils/api.js
=> Add means to start a job (possibly with parameters) from the web UI

server/crypto.go, server/image.go, server/job.go, server/keys.go, server/main.go, server/project.go, server/server.go, server/user.go, server/variant.go
instead of taking a params map and a bodyFunc, the wrapped functions now accept a request struct which embeds the raw request and response and the mux vars.
The struct also defines a parseBody function whiuch parses a json body and a rawBody function which returns the request's raw payload.
=> Rework the server's handler wrapper to make it more flexible

commons/mongo/project.go, commons/types.go, server/project.go, web/src/app.js, web/src/home/homeController.js, web/src/job/jobController.js, web/src/project/projectController.js, web/src/projects.html, web/src/styles.scss, web/src/theme/_colors.scss, web/src/theme/_tables.scss, web/src/utils/api.js, web/src/utils/job-status.html, web/src/utils/job-status.js, web/src/utils/utils.js, web/src/variant/variant.js
Also, whenever the job list is refreshed, the projects last job status also gets updated.
=> Show the number and status of the last job in the sidebar projects

server/variant.go
The strict mode is required for the web app (to the oboe js library in particular) to be able to parse the json in a streaming fashion
=> Support the strict-json mode when streaming a variant's log

commons/mongo/project.go, commons/types.go, server/github.go, server/main.go, server/server.go
This PR handles github authentication for webhooks.
See developer doc https://developer.github.com/webhooks/
=> Handle github hook authentication

commons/mongo/project.go, server/github.go, server/job.go, server/types.go
Now handles
* branches push force
* tags
Closes #232
=> Update github hook management

server/github.go
=> Do not trigger a build when the push is for a deleted branch

commons/mongo/project.go, commons/project.go, orchestration/main.go, orchestration/runner.go, server/main.go, server/variant.go, web/src/variant/_variant.scss, web/src/variant/variant.html
=> Capture the artifacts list of a variant and display them in the web ui

commons/mongo/project.go, commons/scanner.go
By using a custom scanner instead of bufio's one
Fixes #153
Depends on bywan/go-dockercommand#7
=> Handle log lines larger than 64K

web/src/job/_job.scss, web/src/job/_variants.scss, web/src/job/job.html, web/src/theme/_colors.scss, web/src/utils/_job-info.scss
=> Some minor changes in color

commons/project.go
=> Fix a JSON config bug in Variant struct

cli/bzk/bzk.go, cli/bzk/image.go, client/image.go, commons/mongo/image.go, orchestration/parser.go, orchestration/scmfectch.go, server/job.go, server/main.go
This will be needed for orchestration and parser to retrieve the required images using the API instead of mongo
=> Add an API to serve a specific image given its name

commons/config.go, orchestration/parser.go, orchestration/runner.go, orchestration/runner_test.go, parser/generator.go
=> Implement service aliases

cli/README.md, cli/bzk/bzk.go, cli/bzk/client.go, cli/bzk/config.go, cli/bzk/service.go, orchestration/context.go, orchestration/main.go, orchestration/parser.go, orchestration/scmfectch.go, server/context.go, server/job.go, web/gulpfile.js
In order to do things like nark jobs and variants as finished, add SCM info, ...
=> Orchestration now uses the HTTP API instead of mongo

orchestration/parser.go, parser/context.go, parser/main.go, server/main.go
Instead of a hard-coded list of images
=> Parser now use the image API to retrieve the language parser image to use

parser/generator.go
=> Update generator to manage changes in working directory

parser/Dockerfile, parser/generator.go, parser/generator_test.go, parser/main.go, parser/template/Dockerfile, parser/template/bazooka_phase.sh, parser/template/bazooka_run.sh
=> Use templates to generate bzk build scripts and Dockerfile

server/job.go, server/main.go, server/types.go
* Use new json format
* fix the startJob that was blocking
=> Fix bitbucket server hook
