- commons/types.go
- orchestration/main.go
- orchestration/runner.go
- parser/generator.go
- server/main.go
- server/variant.go
This feature relies on the following configuration keys:
* archive: takes a single or a list of globs. The matching files are archived regardless of the result of the build
* archive_success: takes a single or a list of globs. The matching files are archived in case of a successfull build
* archive_failure: takes a single or a list of globs. The matching files are archived in case of a failed build
The archived files are then exposed over http using the following endpoint:
bzk_server:3000/variant/{id}/artifacts/{path}
Where id is the variant id and path the path to an archived artifact.
Fixes #144
> Implement a build artifact archiving mechanism

- cli/bzk/bzk.go
- cli/bzk/client.go
- cli/bzk/project.go
- commons/mongo/project.go
- commons/types.go
- server/main.go
- server/project.go
- server/server.go
This will be useful for the following cases:
* #63 project specific build system: the config can be used to store the build docker image to run
* #145 reuse scm checkout: to configure whether a project has to perform a fresh checkout or update an existing one
* Possibly #129 injecting project specific values into a job
> Add a per-project server-side configuration map

- orchestration/builder.go
- orchestration/main.go
- parser/generator.go
Before, and after parser has generated the variants scripts and Dockerfiles, orchestration used to build the variants concurrently.
Every variant build consisted of copying the variant scripts and Dockerfile to the source directory and launching a docker build of the image.
This obviously is incorrect, as there is only one source directory and multiple variants
The fix makes use of docker's recent ability to use a custom Dockerfile:
We no longer copy the variant files to the source directory.
Instead, the image build is performed using the job root directory as the build context, and individually adding the variant's script files
to the image (using COPY commands in the variant's Dockerfile).
Fixes #155
> Fix a concurrency bug with the parallel image building

- cli/bzk/bzk.go
- cli/bzk/client.go
- cli/bzk/crypto.go
- commons/config.go
- commons/crypto.go
- commons/mongo/crypto.go
- commons/types.go
- orchestration/main.go
- orchestration/parser.go
- orchestration/paths.go
- parser/generator.go
- parser/language_parser.go
- parser/main.go
- parser/paths.go
- server/crypto.go
- server/job.go
- server/main.go
- server/project.go
Do something like that:
```yaml
language: golang
go:
- 1.3.1
after_script:
- echo $TEST_SECURE
- echo $TOTO
env:
- secure: 5d5a074ca963ffedb3e80660f98ae43262e7c58adf40fc31b35a439d7ebdecf2e138b012
- TOTO=1
```
Only env vars can be encrypted
* Each time a new project is created, bazooka generates a key for this project and store it in mongo. Each project has its own key.
* As a user, when you want to encrypt some data, you use `bzk encrypt`
```
Usage: bzk encrypt PROJECT_ID DATA 
Encrypt some data
Arguments:
PROJECT_ID=""   Project id
DATA=""         Data to Encrypt
```
* With the encrypted data returned by this command, you add it where you want in your bazooka.yml, like in the previous example.
* When bazooka starts a job, it will look for every `secure: ...` item during yaml …
> Enable secure content in bazooka.yml

- cli/bzk/client.go
- commons/mongo/project.go
Setting a project config key containing a dot would create a sub document in mongo.
Mongo doesn't support escaping dots in the key names.
The proposed fix is to replace dots with something (// in this case) before submitting them to mongo, and to unescape them back the other way around
Also, the cli submited config values were wrapped into extra quotes.
> Fix dot handling in project config keys and extra quotes around the settings values

- cli/bzk/client.go
- cli/bzk/job.go
- commons/config.go
- commons/types.go
- orchestration/main.go
- orchestration/parser.go
- orchestration/runner.go
- parser/generator.go
- parser/main.go
- server/job.go
We can now use `bzk job start` for injecting parameters to the job:
```
Usage: bzk job start PROJECT_ID [SCM_REF] [--env...]
Start a new bazooka job on a project
Arguments:
PROJECT_ID=""      the project id
SCM_REF="master"   the scm ref to build
Options:
-e, --env=[]string(nil)   define an environment variable for the job
```
E.g.:
```bzk job start my-project my-branch -e A=3 -e B=42```
Permutation can be created by settings multiple times the same variable:
```bzk job start my-project my-branch -e A=3 -e A=5````
Settings defined on the project's configuration map are also injected. 
The `.bazooka.yml` can define mandatory parameters by adding an entry in the env section without value:
```
env:
- A
- B=5
```
`A` has to be defined on the project's configuration map or at the start of the …
> Allow job parameters

- docs/home/project_configuration.md
- mkdocs.yml
- orchestration/main.go
- orchestration/parser.go
- orchestration/paths.go
- orchestration/scmfectch.go
- parser/paths.go
- server/job.go
This is useful for projects with a big footprint, where checkouting could take a couple minutes.
The proposed solution works as follow:
- A project must first be configured to do an update instead of a fresh checkout using the project configuration feature, by setting the "bzk.scm.reuse" key to "true". The cli can be used to this effect: `bzk project config set <project-name> bzk.scm.reuse true`
- When the server receives a start job request, it reads this configuration value. If set to true, a project-level (`$BZK_HOME/build/<project-id>/source`) folder is created if it does not already exist, and gets mounted into orchestration at `/bazooka/source`, on top of the job directory which still gets mounted at `/bazooka`
- The orchestration container is also passed an env var …
> Support scm checkout updating instead of performing a fresh checkout on every build

- .bazooka.yml
Making bazooka images does not depend on external services, and should be a part of the script phase, since building bazooka images is like compiling our application
> Move `make images` in script phase

- web/src/job/job.html
- web/src/job/jobController.js
(one with `go:1.4` and another with `image:my-image` for example), the job would group both in one single column
Fixes #151
> Fix a bug where if the variants of a job had different list of metas

- commons/net.go
- server/main.go
This is done server-side and not in the CLI (as suggested by the linked issue), this way this safeguard works regardless of how the server is started.
Fixes #171
> Wait for mongodb to start accepting TCP connections (for 5s at most) before trying to connect to it

- web/src/job/jobController.js
- web/src/variant/variant.js
jobController.js occasionally throws an error if the variants lists is loaded before the job itself
> Fix JS error in a job page

- cli/bzk/config.go
- cli/bzk/service.go
- commons/mongo/connector.go
- docs/cli/service.md
Add a --mongo-uri option on bzk service start to enable use of an external MongoDB server.
```
bzk service start --mongo-uri=mongodb://user:password@my-mongo-instance:1234/my-database-name
> Enable custom mongo settings

- parser/main.go
as is done in the regulr env config key.
Bazooka now accepts:
```yml
matrix:
exclude:
- go: "1.4"
env: B=testb1
```
Whereas before it only accepted:
```yml
matrix:
exclude:
- go: "1.4"
env:
- B=testb1
```
> Handle inline string values in env exclusions

- commons/config.go
- commons/types.go
- parser/generator.go
- parser/main.go
This solution extends BzkString to make a string instead of a just an alias for string with 3 fields:
* name: the environement variable name
* value: the environement variable value
* secured: a boolean flag indicating if the variable is secured or not
When unmarshalling a `.bazooka.yml`, the custom BzkString unmarshaller fills these fields accordingly.
`BzkString` now also implements the `yaml.Marshaller` interface. This way, when a config struct is persisted to disk, the secured values get encrypted again
When language parser generates the variants bazooka files, and the parser parses them, the secured values are correctly marked so.
Finally, when the parser generates the metadata file for a variant, the secured variables are encrypted before storing them.
Fixes #193
Be sure to test …
> Protect the encrypted values in a job's metadata

- .bazooka.yml
Since these actions are conditionnal, and only done when some
env vars are present, they should be part of the script, and fail
the job if the push fails
> Move push actions in script phase

- commons/types.go
- server/crypto.go
- server/project.go
- server/server.go
Use gopkg.in/bluesuncorp/validator.v5 to validate submitted JSON.
Simply add the validate tag on a field to set constraints:
```
type Project struct {
ScmType    string            `bson:"scm_type" json:"scm_type" validate:"required"`
ScmURI     string            `bson:"scm_uri" json:"scm_uri" validate:"required"`
Name       string            `bson:"name" json:"name" validate:"required"`
ID         string            `bson:"id" json:"id"`
JobCounter int               `bson:"job_counter" json:"job_counter"`
Config     map[string]string `bson:"config" json:"config"`
}
```
We can use all the validators defined here https://godoc.org/gopkg.in/bluesuncorp/validator.v5#hdr-Baked_In_Validators_and_Tags
It's possible to create custom validator if necessary.
I use the package reflect to generate …
> Improve validation: use tagName 'validate' to add constraints on a field

- commons/bzk_string.go
- commons/config.go
- commons/crypto.go
- commons/project.go
- commons/types.go
- commons/yaml.go
Split the humongous types.go into smaller and more focused files.
Also, get rid of code duplication in unmarshalling keys which take one or multiple values
> Reorganize commons

- parser/main.go
Add built-in php support.
PHP runners and parser are on [bazooka-lang-php project](https://github.com/bazooka-ci/bazooka-lang-php).
The PR for the docs: https://github.com/bazooka-ci/docs/pull/7
> Add built-in php support

- cli/bzk/client.go
- cli/bzk/input.go
- cli/bzk/login.go
- cli/bzk/service.go
CLI tries to display a default value when user input is required.
e.g. when the server uri is not defined:
```
▶ bzk project list
Bazooka Server URI [http://192.168.59.103:3000]:
```
or
```
▶ bzk service start
Bazooka Home Folder [/Users/eric/bazooka]:
Docker Socket path [/var/run/docker.sock]:
Bazooka Default SCM private key [/Users/eric/.ssh/id_rsa]:/Users/eric/.ssh/id_custom
```
> CLI tries to display a default value when user input is required.

- cli/bzk/config.go
- cli/bzk/service.go
- bzk service restart == bzk service stop && bzk service start
- Rename tag option by version on bzk service start
- Add --recreate options on bzk service restart which destroy container before restarting it
```
Usage: bzk service restart [--recreate [-swd]]
Restart bazooka
Options:
--recreate        Recreate existing Bazooka containers
-s, --server      Recreate existing server container
-w, --web         Recreate existing web container
-d, --database    Recreate existing database container
```
https://github.com/bywan/go-dockercommand/pull/8 is required.
> Rewrite bzk service

- server/job.go
During a build, the created directories (build, shared source, ...)
were created using 0644 permissions instead of 0755.
What's really weird is that it used to work in VirtualBox VMs, but
fails (which is to be expected) in VMWare VMs.
> Fix created directories permissions

- cli/bzk/service.go
- server/Dockerfile
- server/main.go
In order to fix spurious mongoldb data corruption which can occur with no grace.
The server component was also modified to listen to and handle the SIGTERM signal docker sends to containers when stopping them, to avoid blocking for the duration of the grace period before stopping.
> Add a 5 second grace period when stopping the bazooka containers

- cli/bzk/bzk.go
- cli/bzk/key.go
- cli/bzk/project.go
- client/project_key.go
- commons/mongo/connector.go
- commons/mongo/crypto.go
- commons/mongo/key.go
- commons/mongo/project.go
- commons/mongo/user.go
- server/keys.go
- server/main.go
The API (and therefore the CLI) now only exposes 2 operations: get and set an SCM key on a project.
This PR also includes a bit of cleanup/refactoring on the mongo db code.
> Tweak SCM key handling

- client/client.go
- client/internal.go
- commons/project.go
- server/internal.go
- server/main.go
- server/server.go
This internal API is intended to be used by orchestration to manipulate jobs and variants using only the API instead of mongo.
For the time being, no specific security scheme is applied to the internal API.
The goal is to implement one in the future to restrict this API to the bazooka components and plugins.
> Add an internal API to manipulate jobs and variants

- server/image.go
The error was caused by parsing the json body into a map, whereas the
validator (automatically invoked) expects a struct
> Fix error when registering an image

- cli/bzk/config.go
- cli/bzk/service.go
- commons/log.go
- commons/mongo/project.go
- commons/syslogparser/syslog.go
- commons/syslogparser/syslog_test.go
- orchestration/context.go
- orchestration/main.go
- orchestration/parser.go
- orchestration/runner.go
- orchestration/scmfectch.go
- parser/context.go
- parser/language_parser.go
- server/Dockerfile
- server/context.go
- server/job.go
- server/log.go
- server/main.go
Replaces the old way of capturing logs (stream docker logs to a pipe with a scanner on the reader to write to mongo) with a new one based on docker's syslog logging driver.
* The server listens for TCP connections on port 3001
* Build containers are started configured to stream their logs to that endpoint (`tcp://server:3001`) using the syslog driver and format
* The server parses and stores the logs in mongo
For this feature to work, the server needs to know its address, so that when it starts an orchestration container, it can configure it with the syslog endpoint.
This is set in the `BZK_SYSLOG_URL` in the server.
The CLI was modified to set that variable from the `--syslog-uri` flag (which has a default value of `$BZK_SYSLOG_URL` in the host).
For example:
```
bzk service start …
```
> Use syslog to capture the build log

- commons/container.go
- orchestration/parser.go
- orchestration/runner.go
- orchestration/scmfectch.go
- parser/language_parser.go
- server/job.go
Bazooka will now systematically use a `defer` function to remove containers created during the build of a project
This function is common to all the modules, and is available in `commons/container.go`
Closes #271
> Use defer to remove containers

- cli/bzk/bzk.go
- cli/bzk/config.go
- cli/bzk/service.go
- commons/mongo/connector.go
- commons/net.go
- hack/bazooka-compose/README.md
- hack/bazooka-compose/docker-compose.yml
- hack/capitan/README.md
- hack/capitan/capitan.cfg.sh
- hack/crowdr/README.md
- hack/crowdr/crowdr.cfg.sh
- orchestration/Dockerfile
- orchestration/context.go
- orchestration/parser.go
- orchestration/scmfectch.go
- parser/context.go
- server/context.go
- server/job.go
- server/project.go
- server/server.go
- web/conf/Dockerfile
- web/conf/bzk-web.conf
- web/conf/substitute.sh
- web/conf/wait-for-server.sh
Bazooka used to rely on links to work:
* The DB container was linked into the server container
* The server container was linked into the web container
This PR proposes to replace these links (which are to be considered a
deprecated and legacy feature in Docker) with the usage of bridge
networks:
`bzk service start` will create a `bzk_net` network if it doesn't
exist, and attach the db, server and containers to it for them to be
able to communicate.
The build flow was also modified so that the various build containers
(orchestration, parser, ...) are attached to the same network when
started.
This PR also adds:
* a working docker compose config capable of starting bazooka using docker compose
* a [crowdr](https://github.com/polonskiy/crowdr) config
* a …
> Replace links with Docker 1.9 bridge networks

- .bazooka.yml
- .gitignore
- Makefile
- orchestration/Makefile
- parser/Makefile
- scripts/dev-setup.sh
- scripts/push-bintray.sh
- server/Makefile
Use the go compiler instead, which supports cross-compiling since 1.5
> Get rid of gox
